name: CI - Lint, Test, Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Backend Lint & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cavee2/backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: cavee2/backend/package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm test
        env:
          NODE_ENV: test
  frontend:
    name: Frontend Lint & Test & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cavee2/frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: cavee2/frontend/package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run build
        env:
          GITHUB_PAGES: 'false'
